// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: intertx/intertx.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Salt struct {
	Salt int32 `protobuf:"varint,1,opt,name=salt,proto3" json:"salt,omitempty"`
}

func (m *Salt) Reset()         { *m = Salt{} }
func (m *Salt) String() string { return proto.CompactTextString(m) }
func (*Salt) ProtoMessage()    {}
func (*Salt) Descriptor() ([]byte, []int) {
	return fileDescriptor_8aec9e5496374541, []int{0}
}
func (m *Salt) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Salt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Salt.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Salt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Salt.Merge(m, src)
}
func (m *Salt) XXX_Size() int {
	return m.Size()
}
func (m *Salt) XXX_DiscardUnknown() {
	xxx_messageInfo_Salt.DiscardUnknown(m)
}

var xxx_messageInfo_Salt proto.InternalMessageInfo

func (m *Salt) GetSalt() int32 {
	if m != nil {
		return m.Salt
	}
	return 0
}

// RegistrationQueue -
type RegistrationQueue struct {
	// the addresses ...
	Addresses []github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,rep,name=addresses,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"addresses,omitempty"`
}

func (m *RegistrationQueue) Reset()         { *m = RegistrationQueue{} }
func (m *RegistrationQueue) String() string { return proto.CompactTextString(m) }
func (*RegistrationQueue) ProtoMessage()    {}
func (*RegistrationQueue) Descriptor() ([]byte, []int) {
	return fileDescriptor_8aec9e5496374541, []int{1}
}
func (m *RegistrationQueue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegistrationQueue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegistrationQueue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegistrationQueue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationQueue.Merge(m, src)
}
func (m *RegistrationQueue) XXX_Size() int {
	return m.Size()
}
func (m *RegistrationQueue) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationQueue.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationQueue proto.InternalMessageInfo

func (m *RegistrationQueue) GetAddresses() []github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func init() {
	proto.RegisterType((*Salt)(nil), "intertx.Salt")
	proto.RegisterType((*RegistrationQueue)(nil), "intertx.RegistrationQueue")
}

func init() { proto.RegisterFile("intertx/intertx.proto", fileDescriptor_8aec9e5496374541) }

var fileDescriptor_8aec9e5496374541 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x50, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0xad, 0x45, 0x01, 0x61, 0xb1, 0x10, 0x81, 0x54, 0x65, 0x30, 0x55, 0xa7, 0x2e, 0x89, 0x89,
	0xf8, 0x82, 0x76, 0x64, 0x41, 0x84, 0x8d, 0xcd, 0x76, 0x4e, 0xa9, 0x45, 0x6a, 0x57, 0xbe, 0x0b,
	0x2a, 0x7f, 0xc1, 0x67, 0x31, 0x76, 0x64, 0x42, 0x28, 0xf9, 0x0b, 0x26, 0x44, 0x1c, 0x09, 0xa6,
	0xf7, 0xee, 0x9e, 0xee, 0x3d, 0xbd, 0xe3, 0x57, 0xd6, 0x11, 0x04, 0xda, 0xcb, 0x11, 0xf3, 0x5d,
	0xf0, 0xe4, 0x93, 0xd3, 0x71, 0x4c, 0x2f, 0x6b, 0x5f, 0xfb, 0x61, 0x27, 0x7f, 0x59, 0x94, 0x53,
	0x61, 0x3c, 0x6e, 0x3d, 0x4a, 0xad, 0x10, 0xe4, 0x4b, 0xa1, 0x81, 0x54, 0x21, 0x8d, 0xb7, 0x2e,
	0xea, 0x8b, 0x94, 0x4f, 0x1f, 0x55, 0x43, 0x49, 0xc2, 0xa7, 0xa8, 0x1a, 0x9a, 0xb1, 0x39, 0x5b,
	0x1e, 0x97, 0x03, 0x5f, 0x54, 0xfc, 0xa2, 0x84, 0xda, 0x22, 0x05, 0x45, 0xd6, 0xbb, 0x87, 0x16,
	0x5a, 0x48, 0xee, 0xf9, 0x99, 0xaa, 0xaa, 0x00, 0x88, 0x80, 0x33, 0x36, 0x3f, 0x5a, 0x9e, 0xaf,
	0x8b, 0xef, 0xcf, 0xeb, 0xac, 0xb6, 0xb4, 0x69, 0x75, 0x6e, 0xfc, 0x56, 0x8e, 0x91, 0x11, 0x32,
	0xac, 0x9e, 0x25, 0xbd, 0xee, 0x00, 0xf3, 0x95, 0x31, 0xab, 0x78, 0x5a, 0xfe, 0x79, 0xac, 0xef,
	0xde, 0x3b, 0xc1, 0x0e, 0x9d, 0x60, 0x5f, 0x9d, 0x60, 0x6f, 0xbd, 0x98, 0x1c, 0x7a, 0x31, 0xf9,
	0xe8, 0xc5, 0xe4, 0xe9, 0xe6, 0x9f, 0xe7, 0xd0, 0xd2, 0x6c, 0x94, 0x75, 0x1a, 0x42, 0x63, 0x9d,
	0xb4, 0x46, 0xc9, 0xf1, 0x17, 0x19, 0xed, 0x63, 0x82, 0x3e, 0x19, 0x4a, 0xdd, 0xfe, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xd8, 0x92, 0x1b, 0x31, 0x2c, 0x01, 0x00, 0x00,
}

func (m *Salt) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Salt) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Salt) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Salt != 0 {
		i = encodeVarintIntertx(dAtA, i, uint64(m.Salt))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RegistrationQueue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegistrationQueue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegistrationQueue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Addresses) > 0 {
		for iNdEx := len(m.Addresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Addresses[iNdEx])
			copy(dAtA[i:], m.Addresses[iNdEx])
			i = encodeVarintIntertx(dAtA, i, uint64(len(m.Addresses[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintIntertx(dAtA []byte, offset int, v uint64) int {
	offset -= sovIntertx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Salt) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Salt != 0 {
		n += 1 + sovIntertx(uint64(m.Salt))
	}
	return n
}

func (m *RegistrationQueue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Addresses) > 0 {
		for _, b := range m.Addresses {
			l = len(b)
			n += 1 + l + sovIntertx(uint64(l))
		}
	}
	return n
}

func sovIntertx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIntertx(x uint64) (n int) {
	return sovIntertx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Salt) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIntertx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Salt: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Salt: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Salt", wireType)
			}
			m.Salt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntertx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Salt |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIntertx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIntertx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegistrationQueue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIntertx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegistrationQueue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegistrationQueue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addresses", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntertx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIntertx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIntertx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addresses = append(m.Addresses, make([]byte, postIndex-iNdEx))
			copy(m.Addresses[len(m.Addresses)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIntertx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIntertx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIntertx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIntertx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIntertx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIntertx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIntertx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIntertx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIntertx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIntertx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIntertx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIntertx = fmt.Errorf("proto: unexpected end of group")
)
